### ISSUE TITLE
Warnings on generating autoload files

### ISSUE THREAD

**Issue by kinkod** [Yurunsoft/Guzzle-Swoole#10]
```
composer require yurunsoft/guzzle-swoole
Using version ^1.1 for yurunsoft/guzzle-swoole
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing funkjedi/composer-include-files (1.0.0): Loading from cache
  - Installing yurunsoft/guzzle-swoole (v1.1.5): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Warning:  Uncaught ErrorException: require_once(/var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load.php): failed to open stream: No such file or directory in /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php:4
Stack trace:
#0 /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php(4): Composer\Util\ErrorHandler::handle(2, 'require_once(/v...', '/var/www/school...', 4, Array)
#1 /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php(4): require_once()
#2 /var/www/schoolxplorer/laravel-swoole-app/vendor/composer/autoload_real.php(66): require('/var/www/school...')
#3 /var/www/schoolxplorer/laravel-swoole-app/vendor/composer/autoload_real.php(56): composerRequire06ee6f3c861e8b9030d94e587f89fc05('d9504a38ef5c66c...', '/var/www/school...')
#4 /var/www/schoolxplorer/laravel-swoole-app/vendor/autoload.php(7): ComposerAutoloaderInit06ee6f3c861e8b9030d94e587f89fc05::getLoader()
# in /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php on line 4

Warning: Uncaught ErrorException: require_once(/var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load.php): failed to open stream: No such file or directory in /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php:4
Stack trace:
#0 /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php(4): Composer\Util\ErrorHandler::handle(2, 'require_once(/v...', '/var/www/school...', 4, Array)
#1 /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php(4): require_once()
#2 /var/www/schoolxplorer/laravel-swoole-app/vendor/composer/autoload_real.php(66): require('/var/www/school...')
#3 /var/www/schoolxplorer/laravel-swoole-app/vendor/composer/autoload_real.php(56): composerRequire06ee6f3c861e8b9030d94e587f89fc05('d9504a38ef5c66c...', '/var/www/school...')
#4 /var/www/schoolxplorer/laravel-swoole-app/vendor/autoload.php(7): ComposerAutoloaderInit06ee6f3c861e8b9030d94e587f89fc05::getLoader()
# in /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php on line 4
PHP Fatal error:  main(): Failed opening required '/var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load.php' (include_path='.:/usr/share/php') in /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php on line 4

Fatal error: main(): Failed opening required '/var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load.php' (include_path='.:/usr/share/php') in /var/www/schoolxplorer/laravel-swoole-app/vendor/yurunsoft/guzzle-swoole/src/load_include.php on line 4

```

**Comment by Yurunsoft** [comment]
You must require `guzzlehttp/guzzle` first
